### PR TITLE
removed mutations: to_s -> to_str, to_i -> to_int, to_a -> to_ary, to…

### PR DESCRIPTION
**Pull request by baseballlover723**
…_h -> to_hash, at -> fetch, [] -> at, [] -> fetch

### CODE REVIEW

**Comment by mbj** [comment]
Curious, why?

**Comment by mbj** [comment]
@baseballlover723 If you intend a fork, a PR to the original repository may not be your intention.

As an early review: I do not like to drop these mutations, they are valid semantic reductions, if you do not agree, feel free to fork mutant.

I'll leave this PR open for now, but unless you add some good arguments, I'll have to close it.

**Comment by mbj** [comment]
It appears this is an unintentional duplicate of https://github.com/baseballlover723/mutant/pull/1, hence I'm closing this one. Feel free to discuss.

**Comment by baseballlover723** [comment]
woops, yeah sorry about that

**Comment by mbj** [comment]
@baseballlover723 I'm still curious why you think a mutant fork is less pain than fixing the semantic uncoverage these mutations expose.

Not that mutant is particularly hard to maintain (and so easy to fork) still I think you may choose the wrong trade-off.

**Comment by dkubb** [comment]
> I'm still curious why you think a mutant fork is less pain than fixing the semantic uncoverage these mutations expose.

I'd probably recommend to anyone wanting to remove mutations to understand (or ask) what the purpose of things are before removing them. There's a really strong reason for semantic reductions to exist.

**Comment by baseballlover723** [comment]
Its my team, its remove stuff and we can still use mutant, or don't use mutant at all.

**Comment by mbj** [comment]
> Its my team, its remove stuff and we can still use mutant, or don't use mutant at all.

Feel free to do whatever you want this is OSS, I'm not judging you, just recommending.

**Comment by dkubb** [comment]
> Its my team, its remove stuff and we can still use mutant, or don't use mutant at all.

Yeah, I'm not a maintainer, just a user. I'm not judging either; maybe they'll see some of the benefits and begin to ask why things are the way they are. I think it does point to us needing some documentation on the benefits of semantic reduction within the context of mutation testing though.

**Pull request closed without merging**
