### PR TITLE
Improve fork isolation spec

### PR DESCRIPTION
**Pull request by kbrock**
Stole this from @mbj on minitest branch

My thought is if we take the generic changes off of minitest branch, then in the future, it will be easier to merge minitest

If it makes sense to merge this into master, great. If not, then just close

### CODE REVIEW

**Comment by backus** [comment]
@kbrock is this a dupe of #625?

**Comment by kbrock** [comment]
ugh - didn't see that. thanks

**Comment by mbj** [comment]
> ugh - didn't see that. thanks

It exposes some in-determinism. Flaws in the isolation already present before these specs. Hence it was not merged yet.

**Comment by kbrock** [comment]
@mbj thanks - I am working on a gem with mini test - wanted to flush it out.
So I came back here and said "oh man, maybe I can take a small chip out of the mini-test effort"

**Comment by mbj** [comment]
@kbrock Totally fine. I really hope to find some OSS time, but its unlikely.

**Pull request closed without merging**
