### PR TITLE
add adamantium to test_app gemspecs

### PR DESCRIPTION
**Pull request by kbrock**
Looks like adamantium and rake were missing from the test_app's gemspec

I made these changes so I could:

```
cd test_app
export BUNDLE_GEMFILE=Gemfile.rspec3.2
bundle exec rake spec
bundle exec mutant -I lib -I spec --require test_app --use rspec TestApp::Literal
```

### CODE REVIEW

**Comment by kbrock** [comment]
ugh - line numbers changes. ok. fixed

**Comment by mbj** [comment]
@kbrock Why do you need / want to suppor the following for the test_app:

```
cd test_app
export BUNDLE_GEMFILE=Gemfile.rspec3.2
bundle exec rake spec
```

**Comment by mbj** [comment]
Full +1 for adding adamantium as dependency, just curious for the need to add a Rakefile. If you'd had broken up the commits to only contain "one semantic change" (one for adding the missing adamantium dep, one for adding the Rakefile) I'd have cherry-picked your adamantium commit already to master.

Maybe its worth you break up the commits anyway. I like each commit does only one self-contained atomic change to the code base & builds on CI.

**Comment by kbrock** [comment]
This is a test app. running rake spec and mutant in it should work fine.

pulled out that change and changed title

**Comment by mbj** [comment]
> Is it worth adding another PR with Gemfile changes to add rake?

I personally never use rake on the test app. Will you?

**Pull request merged**
