### PR TITLE
Update integrations.yml to reflect rubySpec update

### PR DESCRIPTION
**Pull request by mjago**

### CODE REVIEW

**Comment by backus** [comment]
Odd. Looks like `library/stringscanner/getch_spec.rb` is still producing an error

**Comment by mjago** [comment]
Hmm it failed with `Expected to encounter #<Parser::SyntaxError: literal contains escape sequences incompatible with UTF-8> while mutating ` - if it was `expected' presumably it thought it was an exclusion no?

**Comment by backus** [comment]
Yeah it is saying that it expected a utf-8 error in `getch_spec` but none were raised

**Comment by mjago** [comment]
Huh looks like I may have sent you a duff PR and re-introduced:
`
- library/stringscanner/getch_spec.rb		
- library/stringscanner/shared/get_byte.rb
`

**Comment by mjago** [comment]
@backus looks like I forgot to fetch your master before making the new pr branch. I'm surprised your github diff didn't show it though. I blame magit (and its been one of those days) :flushed: It checks ok now. Sorry for the noise!

**Comment by backus** [comment]
No problem. Could you do `git fetch origin && git rebase origin/master` to remove the merge commit?

**Comment by mjago** [comment]
I've re-submitted.

**Pull request closed without merging**
