### PR TITLE
Add support for RSpec 3.7

### PR DESCRIPTION
**Pull request by damireh**
This PR updates the RSpec dependency to allow RSpec`< 3.8.0`

### CODE REVIEW

**Comment by damireh** [comment]
Failing test seems to be unrelated

```
Failed examples:

rspec './spec/integration/mutant/corpus_spec.rb[1:1]' # Mutant on ruby corpus rubyspec does not fail on mutation generation

Randomized with seed 49428

/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.5.4/lib:/usr/local/bundle/gems/rspec-support-3.5.0/lib /usr/local/bundle/gems/rspec-core-3.5.4/exe/rspec --pattern spec/integration/\*\*/\*_spec.rb failed
Exited with code 1
```

**Comment by mbj** [comment]
@damireh The spec failure is indeed unrelated, but needs to be addressed first.

**Comment by maximeg** [comment]
Would be appreciated :)

**Comment by mbj** [comment]
@zaidan Can you take over that one, rebase it on top of master and PR in separate? @damireh if you beat @zaidan to it be my guest.

**Comment by zaidan** [comment]
@damireh great thx

**Pull request merged**
