### PR TITLE
Cleanup defined mutations

### PR DESCRIPTION
**Pull request by mbj**
As a followup to #399, fixing issues I did not spotted on review.

### CODE REVIEW

**Comment by mbj** [comment]
//cc @backus I discovered this after merging #399, and will merge it after CI passed. Just to let you know.

**Comment by backus** [comment]
Thanks.  Why don't we emit `N_FALSE`?

**Comment by mbj** [comment]
> Thanks. Why don't we emit N_FALSE?

Part of the `emit_singletons` implementation.

**Comment by backus** [comment]
Ah alright makes sense

**Pull request merged**
