### PR TITLE
Add support for rspec-3.6

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by mbj** [comment]
Code wise I'm fine with this. Merging in case the build is green.

**Comment by mbj** [comment]
@krzysiek1507 Turns out the build is red for reasons that are not part of the PR. I've to fix the build first. The build is red as the rubyspec corpus tests shows a problem in `parser` or `unparser`. 

I dunno when I've time to fix the build. I normally only work on mutant when being blocked by clients requirements on it. We are not blocked right now, but will when updating to rspec. Hence I've to ask for some (a lot) patience. My OSS time budget outside of clients requirements is essentially 0 these days.

**Comment by krzysiek1507** [comment]
Ok, thanks!

**Comment by jekuta** [comment]
I'd like to use mutant with rspec 3.6 so I took a shot a fixing the build. I created a PR with the fix https://github.com/mbj/mutant/pull/711

**Comment by mbj** [comment]
@jekuta Thx for creating that PR, my OSS time is so limited any help is really appreciated.

**Comment by mbj** [comment]
I'll close this PR, and cherry-pick its commit into a branch I control rebased on top of master that has the build fixed. Thx for @jekuta to do the hard part of the job.

**Comment by krzysiek1507** [comment]
I can rebase it now.

**Comment by krzysiek1507** [comment]
Rebased!

**Comment by mbj** [comment]
@krzysiek1507 Lol, nice. I simply did not assume you could do it that fast ;)

**Comment by mbj** [comment]
*as I had to assume we live in different timezones ETc, the chances where so odd I simply defaulted to do it by myself and naturally preserving your ownership

**Comment by mbj** [comment]
Unexpected OSS awesomeness today, thx!

**Comment by mbj** [comment]
So time for a release.

**Comment by krzysiek1507** [comment]
Thanks!

**Comment by mbj** [comment]
@krzysiek1507 Are you actually using mutant for spree?

**Comment by krzysiek1507** [comment]
No. I'm not sure if it was used in the past or only added to gemfile

**Comment by mbj** [comment]
@krzysiek1507 At the time I was up-streaming fixes to spree I added it to not constantly have to add it to confirm a change. I was surprised seeing effort from someone on spree bumping its dependencies, hence I ask.

**Comment by mbj** [comment]
Changes released as `mutant{,-rspec}-0.8.13`.

**Pull request merged**
