### PR TITLE
Fix all typos

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by mbj** [comment]
@davydovanton I'm sure its not all typos. But its significant amount of typos ;) Thx. I'll merge once green.

**Comment by davydovanton** [comment]
nope, I checked all repo by codespell :smiley:

**Comment by mbj** [comment]
I'm sure this pending PR does fix some you did not fix. https://github.com/mbj/mutant/pull/364/files

**Comment by mbj** [comment]
Actually, the ones I think you did not fixed are not on master. Sorry ;)

**Comment by davydovanton** [comment]
hmmm, okay. Thanks for merge :tada:

**Comment by mbj** [comment]
> Thanks for merge

Thx for contribution.

**Pull request merged**
