### PR TITLE
Add mutation `def foo(*args); end` into `def foo(*args); args = []; end`

### PR DESCRIPTION
**Pull request by backus**

### CODE REVIEW

**Comment by backus** [comment]
This should be ready for review @mbj and @dkubb. I'd love some advice on reducing duplication between `Node::Define#emit_optarg_body_assignments` and `Node::Define#emit_restarg_body_mutation`.

**Comment by mbj** [comment]
@backus As I merged 2 other PRs this one does not apply cleanly anymore (likely a conflict in Chanelog) chances you can rebase for me?

**Comment by backus** [comment]
Sure



—

**Comment by backus** [comment]
Should be rebased now @mbj

**Comment by mbj** [comment]
Sorry for the noise. But master at the time you rebased was broken due the "rolling devtools updates", really need to begin doing gem releases of devtools to make the builds more stable. Do you mind rebasing again?

**Comment by backus** [comment]
Sure

**Comment by backus** [comment]
Rebased.

**Pull request merged**
