### PR TITLE
Add mutation `A = true` -> `remove_const :A`

### LINKED ISSUE #109: Add Mutation: A = true -> remove_const :A
Like #108 this will expose cases where the same constant is declared with the same value in a parent class.

### PR DESCRIPTION
**Pull request by backus**
closes #109

### CODE REVIEW

**Comment by backus** [comment]
I don't think this is up to par to be merged right now, but after trying to find similar mutations I could base this off of I wasn't sure how to better approach this one.  Opening this PR so @mbj can see this before I have to go offline for the rest of the day

**Comment by mbj** [comment]
@backus You touched a subject that did not have full mutation coverage. Would be cool if you could backfill that one (or kill the exposed code).

Mutant recently got stable on self hosting, so this kinds of holes where not be detectable early.

**Comment by mbj** [comment]
@backus BTW For consistency lets prefix future feature branch names with `feature/`? (No need to change this on that PR, just mentioning).

**Comment by backus** [comment]
Sure thing.  Don't use the prefixing myself so I wasn't sure what qualified as a feature 



—

**Comment by mbj** [comment]
> Sure thing.  Don't use the prefixing myself so I wasn't sure what qualified as a feature

Its tagged `enchancement` so its a feature. I'd actually love to change the prefix to mirror this. //cc @dkubb Your opinion on this?

**Comment by dkubb** [comment]
@mbj I am ok with using `enhancement` as a prefix instead of `feature`. I do think we should add a `fix` tag though, since I think that's better than tagging a pull request as a `bug`.

**Comment by backus** [comment]
Looking at the conditional 

```ruby
emit_value_mutations if value
```

I'm not sure when value would ever be falsey

**Comment by backus** [comment]
@dkubb would you be able to comment? Looks like you added that line in 1e14b7f7

**Comment by mbj** [comment]
> I'm not sure when value would ever be falsey

It will not, you can safely killl the conditional. An attribute assignment will *always* have a value. The moment hat code was written and reviewed mutant was not targetable at itself `--zombe` flag did not exist. This side effect is a typical find of mutation testing.

**Comment by dkubb** [comment]
> @dkubb would you be able to comment?

Sorry, I have no idea what I was thinking there. It could be a left-over artifact. If I didn't write a spec for it, then I would suggest just removing the conditional. We should discover pretty quickly during usage if the code has an actual purpose.

**Comment by backus** [comment]
CI green @mbj if you want to take another look

**Comment by backus** [comment]
I made this change

```diff
@@ -6,3 +6,12 @@
   mutation 'A = nil'
   mutation 'remove_const :A'
 end
+
+Mutant::Meta::Example.add do
+  source 'self::A = true'
+
+  mutation 'self::A__MUTANT__ = true'
+  mutation 'self::A = false'
+  mutation 'self::A = nil'
+  mutation 'self.remove_const :A'
+end
```

in order to test that `cbase` was being preserved. Previously I had

```ruby
# Emit remove_const
#
# @return [undefined]
#
# @api private
def emit_remove_const
  emit(s(:send, nil, :remove_const, s(:sym, name)))
end
```

which would have broken something like `self::A = true` I believe.

**Comment by mbj** [comment]
@backus Thx.

**Pull request merged**
