### PR TITLE
Add a mutation from `a != b` to `!a.eql?(b)` and `!a.equal?(b)`.

### PR DESCRIPTION
**Pull request by backus**
Opening a WIP PR for this since I'm not sure how to go about implementing #270 at the moment.  The `mutator/node/send.rb` class seems like an inappropriate place to implement this so I wanted to get some input before I invested time on another implementation

### CODE REVIEW

**Comment by backus** [comment]
Gave this mutation a stab @mbj and @dkubb if you would like to take a look.  

I'd be happy to kill the flagged mutations [here](https://github.com/mbj/mutant/blob/master/lib/mutant/mutator/node/send/binary.rb#L22), but I'm not sure I can think of a case where the right hand would be a splat

**Comment by backus** [comment]
I think the splat conditional was introduced because `BINARY_METHOD_OPERATORS` included `:[]` and `:[]=` at the time it was committed: [constants.rb#L12-L13](https://github.com/mbj/mutant/blob/8b7be8a565c0aa221e3a008e64282950c2aa1327/lib/mutant/constants.rb#L12-L13)

**Comment by dkubb** [comment]
> I'd be happy to kill the flagged mutations here, but I'm not sure I can think of a case where the right hand would be a splat

I think @mbj will need to comment on what cases where the right hand would be a splat, but I had one comment about killing the specific mutation. I'd recommend killing it in it's own commit *before* this one, and then add your change in a separate commit; keeping the feature addition separate from "fixing" the mutation coverage.

There's a 50/50 chance you were going to do this anyway, but I figured I'd mention it in case you hadn't thought about it -- I know it's common for some people to commit code once they've got something working. What @mbj and I have been doing for a while is committing the smallest unit of change we possible can that provides an incremental improvement in the project quality, and fits a specific "theme". That is, we try to separate commits that refactor code, from commits that add functionality, and commits that fix a bug, or remove functionality, and so on.

It's often that when adding new functionality you end up refactoring code to make the addition easier. We would tend to split those into (at least) two commits; one to refactor the code and one to add it. In this specific case we have a situation where specs need to be added to fix a lack of mutation coverage on a method, and there's a feature addition; again we'd split them up.

One side effect of this approach is that we find it much easier to review each other's work. We can walk through the commits and kind of understand each individual transformation in isolation. There's nothing worse than looking at a huge diff, and trying to sort out whitespace fixes, from code removal, refactorings and feature additions. When it's all mixed together like that, you can't really make sense of what the author was trying to do (not saying that what you're doing here, your commits are small and awesome, just giving a more common example I think everyone's seen).

**Comment by backus** [comment]
I agree with all of that @dkubb.

> I'd recommend killing it in it's own commit before this one, and then add your change in a separate commit

I committed the removed conditional separately.  I can reorder the commits now

**Comment by dkubb** [comment]
Just to add a bit more to my last comment.. one thing we also do that helps keep things on target with our commits is that we follow the advice in http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html on commit message structure. In particular writing the summary in the recommended imperative style has naturally nudged us in the direction of starting the summary using a small set of keywords that match the theme of the commit and help us keep it single purposed.

One project @mbj and I collaborate on at work on has an interesting set of keywords on the git commit message summaries. Here's the keywords for the last 1000 commits in that project:

```shell
$ git log --pretty=oneline | head -1000 | cut -d' ' -f2 | sort | uniq -c | sort -nr
    298 Merge
    219 Add
    111 Fix
     97 Remove
     54 Change
     48 Upgrade
     37 Refactor
     21 Update
     19 Kill
     16 Revert
     15 Move
     10 Use
      9 Replace
      9 Rename
      7 Improve
      5 Reduce
      3 Make
      2 Prevent
      2 Disable
      2 Allow
      1 Track
      1 Slightly
      1 Setup
      1 Set
      1 Reorganise
      1 Perform
      1 Lift
      1 Introduce
      1 Handle
      1 Enable
      1 Downgrade
      1 Deduplicate
      1 Create
      1 Commenting
      1 Amend
      1 Align
```

I think some of the ones at the last half of the list are questionable, and probably should've been caught during code review, you can see how we structure things more closely.

I don't know if our approaches are better or worse than the norm, but they work for us and I've seen improvements in our code review process and the general quality of our pull requests, so I figured I'd pass them along.

I really need to get busy blogging this stuff ;)

**Comment by backus** [comment]
I'll rewrite the commits!

**Comment by dkubb** [comment]
> I'll rewrite the commits!

Haha, I wasn't saying that, just specifying how we do things. It's more important to keep the commits separated by the kind of transformation they are ;)

**Comment by backus** [comment]
Only takes me a minute though and I respect the conventions.  Markus is definitely asleep so the build time isn't a big deal either :smile:

**Comment by mbj** [comment]
> I think @mbj will need to comment on what cases where the right hand would be a splat, but I had one comment about killing the specific mutation. I'd recommend killing it in it's own commit before this one, and then add your change in a separate commit; keeping the feature addition separate from "fixing" the mutation coverage.

Removing the guard is correct. AFAIK there is no way the `Mutator::Node::Send::Binary` can be hit with an RHS splat as we have a dedicated dispatch for the various "send forms" ruby can have before the mutator gets invoked.

Ack on moving that to a separate commit. But we should make sure we build it also on CI. At the time of posting on the last commit pushed was build.

@backus You might want to look into the utility we wrote `git-push-each` that pushes each commit separately, making sure each one gets a build and is green. Find that utility here: https://github.com/dkubb/git-tools

**Comment by dkubb** [comment]
The need to push each commit individually in order to build them is mostly a side effect of github and CircleCI's integration. I wish it were possible to tell one or both services "build all the commits, not just the last one". The tool I wrote works-around the limitation by pushing each commit individually one at a time, causing a CircleCI build to be triggered for each commit.

**Comment by mbj** [comment]
@dkubb Much better description than mine. Thx for that.

**Comment by backus** [comment]
I like the tools.  Not sure how to run `git-push-each` now that the commits are already up

**Comment by backus** [comment]
Ah I had to rebase anyways.

**Comment by dkubb** [comment]
@backus I plan to add a `--force` option when I figure out a nice clean way to add it, but for now you could temporarily change line 13 to the following:

```bash
commits=$(git rev-list HEAD "^$remote/$parent" --reverse)
```

You can then run it as `git push-each` or `git push-each $branch` if the parent branch is something other than master.

**Comment by dkubb** [comment]
> Ah I had to rebase anyways.

Ahh ok, even better. Once you rebase on top of master `git push-each` should just work as you'd expect.

**Comment by backus** [comment]
Rebased and ready for another pass @mbj

**Pull request merged**
